#!/bin/bash

setup_wechall() {
    echo "Setting up WeChall..."

    echo -n "WeChall User:  "
    read WECHALLUSER

    echo -n "WeChall Token: "
    read WECHALLTOKEN

    echo '#!/bin/sh' > ~/.wechall
    echo "WECHALLUSER=\"$WECHALLUSER\"" >> ~/.wechall
    echo "WECHALLTOKEN=\"$WECHALLTOKEN\"" >> ~/.wechall
    echo "Configuration stored in ~/.wechall"

    # Reload
    source ~/.wechall
}

otw() {
    # Check for sshpass
    command -v sshpass
    if [ $? -ne 0 ]; then
        echo "You need to install sshpass for this program to work."
        return
    fi
    
    # Set up the .otwpass file
    if [ ! -e ~/.otwpass ]; then
        touch ~/.otwpass
        for GAME in bandit leviathan narnia behemoth utumno maze manpage; do
            echo "${GAME}0 ${GAME}0" >> ~/.otwpass
        done
    fi

    # Check that a valid level was given
    if [[ ! "$1" =~ '[a-z]+[0-9]+' ]]; then
        echo "Please enter a SSH-capable OverTheWire level in the format $GAME$LEVEL"
        echo "For example: bandit0, leviathan2, manpage4"
        return
    fi

    # Extract the game and level
    # I know this is a shit way of doing this, but at least it works
    GAME=`sed -r 's/([a-z]+)([0-9]+)/\1/' <<< "$1"`
    LEVEL=`sed -r 's/([a-z]+)([0-9]+)/\2/' <<< "$1"`
    shift

    # Try to get the password entry from the .otwpass file
    # If it exists, compact the spacing down to a single space
    PASS_STRING="`grep -E "$GAME$LEVEL +[a-zA-Z0-9]+" ~/.otwpass | sed -r 's/ +/ /'`"

    # Extract the password
    # From the .otwpass file
    if [ -n "$PASS_STRING" ]; then
        PASS="`cut -d' ' -f2 <<< $PASS_STRING`"
    # From a command-line argument
    elif [ -n "$1" ]; then
        PASS="$1"
        shift
    # Whoops, couldn't get a password.  Oh well.
    else
        echo "Please provide a password for $GAME$LEVEL: $0 $GAME$LEVEL <password>"
        return
    fi

    # Update WeChall?
    COMMAND=""
    if [ -n "$1" ]; then
        if [[ "$1" == "wechall" ]]; then
            COMMAND="wechall; exit"
        fi
    fi

    # Try to login
    sshpass -p"$PASS" ssh -oStrictHostKeyChecking=no -oSendEnv=WECHALLUSER -oSendEnv=WECHALLTOKEN $GAME$LEVEL@$GAME.labs.overthewire.org "$COMMAND"

    # Check if the password was wrong
    RET=$?
    if [ $RET -eq 5 ]; then
        echo "The password $PASS is incorrect for $GAME$LEVEL."
    # If the password was right and we got it from the command-line, save it
    elif [[ ( -z "$PASS_STRING" ) && ( $RET -eq 0 ) ]]
    then
        PASS_STRING="$GAME$LEVEL $PASS"
        echo $PASS_STRING >> ~/.otwpass
        echo "Stored password $PASS for $GAME$LEVEL."
    fi
}

if [ -e ~/.wechall ]; then
    source ~/.wechall
fi
